version: '3.7'
services:
  api:
    build: .
    image: final-project-6-api
    restart: always
    ports:
      - 8000:8000
    environment:
      MONGO_DATABASE: ${MONGO_DB_NAME}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - mongodb
      - rabbitmq

  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongo-data:/data/db
      - ./db-init/:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATEBASE}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}

  rabbitmq:
    image: rabbitmq:3-management
    hostname: "rabbitmq-server"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment: 
      MONGO_DATABASE: ${MONGO_DB_NAME}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      
volumes:
  mongo-data: